spring:
  application:
    name: eureka-server
server:
  port: 1111
eureka:
  instance:
    hostname: server1
    metadataMap:
      instanceId: ${spring.application.name}:${random.value}
  client:
    serviceUrl:
      defaultZone: http://server2:1112/eureka/,http://server3:1113/eureka/